"""remove user role

Revision ID: 8d47cbf4dd02
Revises: 009acf70ec7e
Create Date: 2023-07-03 15:56:09.367544

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d47cbf4dd02'
down_revision = '009acf70ec7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), nullable=False))
    op.add_column('user', sa.Column('is_stuff', sa.BOOLEAN(), nullable=False))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', postgresql.ENUM('admin', 'stuff', 'user', name='role'), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_stuff')
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###
