"""Rename Team model

Revision ID: 1835ef19ad48
Revises: 2933050b1bc6
Create Date: 2023-11-16 13:59:57.061416

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1835ef19ad48'
down_revision = '2933050b1bc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('teamsgames',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('team_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('answer_command_id_fkey', 'answer', type_='foreignkey')
    op.drop_table('commandsgames')
    op.drop_table('command')
    op.add_column('answer', sa.Column('team_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'answer', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_column('answer', 'command_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('command_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key('answer_command_id_fkey', 'answer', 'command', ['command_id'], ['id'], ondelete='CASCADE')
    op.drop_column('answer', 'team_id')
    op.create_table('commandsgames',
    sa.Column('command_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('command_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['command.id'], name='commandsgames_command_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name='commandsgames_game_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='commandsgames_pkey')
    )
    op.create_table('command',
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='command_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='command_pkey'),
    sa.UniqueConstraint('title', name='command_title_key')
    )
    op.drop_table('teamsgames')
    op.drop_table('team')
    # ### end Alembic commands ###
