"""added field command_number in CommandsGames

Revision ID: 2933050b1bc6
Revises: 6fc69472d4de
Create Date: 2023-07-13 11:43:31.952259

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2933050b1bc6'
down_revision = '6fc69472d4de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commandsgames', sa.Column('command_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commandsgames', 'command_number')
    # ### end Alembic commands ###
